[package]
name = "transport-map-rest-rust"
version = "0.1.0"
authors = ["Artsiom <artkostm@gmail.com>"]

[dependencies.nickel]
git = "https://github.com/nickel-org/nickel.rs.git"
[dependencies]
serde_json = "0.9"